// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StackOverFlow.Infrastructure;

#nullable disable

namespace StackOverFlow.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240417062125_AddNewCOlumnFOrFindUser")]
    partial class AddNewCOlumnFOrFindUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuestionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("QuestionsTags", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnswerTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnsweredByCreatorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AnsweredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnswerCount")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriedApproach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepliedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplyByEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReplyTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de8d8d12-81b2-4a68-8c6b-c3fe3f962381"),
                            Description = "JavaScript is a server-side language.",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("f6d89093-c70a-4c9e-9f2a-e2e90c19aa24"),
                            Description = "C# is a programming language developed by Microsoft.",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("69bba39d-bc3e-4512-b141-ab501a561223"),
                            Description = "Python is a high-level, interpreted programming language.",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("2b19619d-fc28-48b3-84ab-7902d1139bf1"),
                            Description = "Java is a widely used programming language.",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("c01a7582-6d0e-419c-bff8-d2e43a10b43a"),
                            Description = "HTML is the standard markup language for creating web pages.",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("9292004f-e852-4b9c-a315-ce809f03bdd7"),
                            Description = "CSS is used for styling web pages.",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("6de7102a-39e6-4a58-9778-428765853ce1"),
                            Description = "SQL is used for managing relational databases.",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("b4fdaa93-715b-42a5-a6e5-bca21f065a29"),
                            Description = "React is a JavaScript library for building user interfaces.",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("8bbd8bb6-ae63-4cce-b3d6-56f7bdfdf5c8"),
                            Description = "Angular is a platform and framework for building single-page client applications using HTML and TypeScript.",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("8502fda0-37a4-42fe-829d-5d6a10d8204e"),
                            Description = "Node.js is an open-source, cross-platform JavaScript runtime environment that executes JavaScript code outside of a browser.",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("25611ab0-5c41-4fb5-8592-1c18581fa27d"),
                            Description = "Ruby is a dynamic, reflective, object-oriented, general-purpose programming language.",
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("0c19bb0c-7bc9-472d-814b-c1178b5e6bc3"),
                            Description = "PHP is a general-purpose scripting language especially suited to web development.",
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("a70aebb0-9b31-40f5-a9be-199e1c1916dc"),
                            Description = "Swift is a powerful and intuitive programming language for macOS, iOS, watchOS, and tvOS.",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("c64a1c9c-4429-401a-987c-785b7456737c"),
                            Description = "Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.",
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("52200b18-921a-49ce-86f3-59a2e978cfca"),
                            Description = "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript.",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("343f5941-a7cf-45df-abe3-4c97820ffcd4"),
                            Description = "Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.",
                            Name = "Rust"
                        },
                        new
                        {
                            Id = new Guid("97ea8d10-2e83-4392-aeb5-5865aec9b776"),
                            Description = "Kotlin is a statically typed programming language that runs on the Java Virtual Machine and can be compiled to JavaScript source code or use the LLVM compiler infrastructure.",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("44a00057-9f3c-4c8f-b42b-0695c8761a7c"),
                            Description = "Scala is a general-purpose programming language providing support for functional programming and a strong static type system.",
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("63a76b6d-9972-4ef3-9c44-7a1917fab82e"),
                            Description = "Ruby on Rails, or Rails, is a server-side web application framework written in Ruby under the MIT License.",
                            Name = "Ruby on Rails"
                        },
                        new
                        {
                            Id = new Guid("5d8036a1-8af6-45a3-8833-07b8180ed06a"),
                            Description = "Objective-C is a general-purpose, object-oriented programming language that adds Smalltalk-style messaging to the C programming language.",
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = new Guid("c932ab93-355d-405f-8cbe-1eb2d61bf03c"),
                            Description = "Vue.js is an open-source JavaScript framework for building user interfaces and single-page applications.",
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = new Guid("64a7b207-36a7-45e3-8a9b-82f2c49076ae"),
                            Description = "ASP.NET is an open-source web framework for building modern web apps and services with .NET.",
                            Name = "ASP.NET"
                        },
                        new
                        {
                            Id = new Guid("c6aabe33-559e-4bf3-b7cb-b28bb612a658"),
                            Description = "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.",
                            Name = "Django"
                        });
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("StackOverFlow.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackOverFlow.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Answer", b =>
                {
                    b.HasOne("StackOverFlow.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Reply", b =>
                {
                    b.HasOne("StackOverFlow.Domain.Entities.Answer", "Answer")
                        .WithMany("Replies")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackOverFlow.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationRoleClaim", b =>
                {
                    b.HasOne("StackOverFlow.Infrastructure.Membership.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserClaim", b =>
                {
                    b.HasOne("StackOverFlow.Infrastructure.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserLogin", b =>
                {
                    b.HasOne("StackOverFlow.Infrastructure.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserRole", b =>
                {
                    b.HasOne("StackOverFlow.Infrastructure.Membership.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackOverFlow.Infrastructure.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackOverFlow.Infrastructure.Membership.ApplicationUserToken", b =>
                {
                    b.HasOne("StackOverFlow.Infrastructure.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Answer", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("StackOverFlow.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
